const ErrorList={
  "auth/claims-too-large": "An unexpected error occurred. Please try again later.",
  "auth/email-already-exists": "This email address is already in use by another account. Please try logging in.",
  "auth/id-token-expired": "Your session has expired. Please log in again for your security.",
  "auth/id-token-revoked": "Your session is no longer valid. Please log in again.",
  "auth/insufficient-permission": "An unexpected error occurred. Please try again later.",
  "auth/internal-error": "We're having some trouble on our end. Please try again in a few moments.",
  "auth/invalid-argument": "An unexpected error occurred. Please try again.",
  "auth/invalid-claims": "An unexpected error occurred. Please try again later.",
  "auth/invalid-continue-uri": "An error occurred. Please restart the process.",
  "auth/invalid-creation-time": "An unexpected error occurred. Please try again.",
  "auth/invalid-credential": "The login information you entered is incorrect. Please check and try again.",
  "auth/invalid-disabled-field": "An unexpected error occurred. Please try again later.",
  "auth/invalid-display-name": "The display name you entered is not valid. Please choose another one.",
  "auth/invalid-dynamic-link-domain": "An error occurred. Please restart the process.",
  "auth/invalid-email-verified": "An unexpected error occurred. Please try again.",
  "auth/invalid-hash-algorithm": "An unexpected error occurred. Please try again later.",
  "auth/invalid-hash-block-size": "An unexpected error occurred. Please try again later.",
  "auth/invalid-hash-derived-key-length": "An unexpected error occurred. Please try again later.",
  "auth/invalid-hash-key": "An unexpected error occurred. Please try again later.",
  "auth/invalid-hash-memory-cost": "An unexpected error occurred. Please try again later.",
  "auth/invalid-hash-parallelization": "An unexpected error occurred. Please try again later.",
  "auth/invalid-hash-rounds": "An unexpected error occurred. Please try again later.",
  "auth/invalid-hash-salt-separator": "An unexpected error occurred. Please try again later.",
  "auth/invalid-id-token": "Your session is not valid. Please log in again.",
  "auth/invalid-last-sign-in-time": "An unexpected error occurred. Please try again.",
  "auth/invalid-page-token": "An unexpected error occurred. Please try again.",
  "auth/invalid-password": "The password is not valid. It must be at least 6 characters long.",
  "auth/invalid-password-hash": "An unexpected error occurred. Please try again later.",
  "auth/invalid-password-salt": "An unexpected error occurred. Please try again later.",
  "auth/invalid-phone-number": "The phone number you entered is not valid. Please check the format.",
  "auth/invalid-photo-url": "The photo URL is not valid. Please try another image.",
  "auth/invalid-provider-data": "An error occurred while signing in. Please try again.",
  "auth/invalid-provider-id": "An error occurred while signing in. Please try again.",
  "auth/invalid-oauth-responsetype": "An error occurred while signing in with that service. Please try again.",
  "auth/invalid-session-cookie-duration": "An unexpected error occurred. Please try again.",
  "auth/invalid-uid": "An unexpected error occurred. Please try again.",
  "auth/invalid-user-import": "An unexpected error occurred. Please try again.",
  "auth/maximum-user-count-exceeded": "We are unable to create new accounts at this time. Please try again later.",
  "auth/missing-android-pkg-name": "An unexpected error occurred on this device. Please try again.",
  "auth/missing-continue-uri": "An error occurred. Please restart the process.",
  "auth/missing-hash-algorithm": "An unexpected error occurred. Please try again later.",
  "auth/missing-ios-bundle-id": "An unexpected error occurred on this device. Please try again.",
  "auth/missing-uid": "An unexpected error occurred. Please try again.",
  "auth/missing-oauth-client-secret": "An error occurred while signing in with that service. Please try again.",
  "auth/operation-not-allowed": "This sign-in method is currently disabled.",
  "auth/phone-number-already-exists": "This phone number is already registered. Please log in instead.",
  "auth/project-not-found": "An unexpected error occurred. Please try again later.",
  "auth/reserved-claims": "An unexpected error occurred. Please try again later.",
  "auth/session-cookie-expired": "Your session has expired. Please log in again.",
  "auth/session-cookie-revoked": "Your session is no longer active. Please log in again.",
  "auth/too-many-requests": "You have made too many attempts in a short time. Please wait a moment before trying again.",
  "auth/uid-already-exists": "An unexpected error occurred. Please try again.",
  "auth/unauthorized-continue-uri": "An error occurred. Please restart the process.",
  "auth/user-not-found": "No account was found with these details. Please check your information or sign up."
}
